yes | apt update -y
yes | apt upgrade -y
yes | apt install x11-repo
yes | apt install tur-repo
yes | apt install wget
yes | apt install unzip
yes | apt install openjdk-17
yes | apt install kotlin
yes | apt install gradle
yes | apt install git
yes | apt install apksigner
yes | apt install aapt2
yes | apt update -y
yes | apt upgrade -y
